name: Devenv CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: cachix/install-nix-action@v31

      - uses: cachix/cachix-action@v17
        with:
          name: devenv

      - name: Install devenv
        run: nix profile add nixpkgs#devenv

      - name: Build frontend
        run: devenv shell -- build-frontend

      - name: Upload script.js
        uses: actions/upload-artifact@v7
        with:
          name: frontend-build-script
          path: script.js
          archive: false

      - name: Upload index.html
        uses: actions/upload-artifact@v7
        with:
          name: frontend-build-index
          path: index.html
          archive: false

      - name: Build container image
        run: |
          devenv container copy app --registry docker-daemon:
          docker save app:latest -o app.tar.gz

      - name: Upload container image
        uses: actions/upload-artifact@v7
        with:
          path: app.tar.gz
          archive: false

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Download script.js
        uses: actions/download-artifact@v8
        with:
          name: script.js
          path: .

      - name: Download index.html
        uses: actions/download-artifact@v8
        with:
          name: index.html
          path: .

      - name: Download app.tar.gz
        uses: actions/download-artifact@v8
        with:
          name: app.tar.gz
          path: .

      - name: Update script.js URL
        run: |
          sed -i \
            "s|script\.js|https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/script.js|g" \
            index.html

      - name: Create GitHub release
        uses: softprops/action-gh-release@v3
        with:
          files: |
            script.js
            index.html
            app.tar.gz
